In [1]:
# 标准安装的Python中用列表(list)保存一组值，可以用来当作数组使用，不过由于列表的元素可以是任何对象，因此列表中所保存的是对象的指针。
# 这样为了保存一个简单的[1,2,3]，需要有3个指针和三个整数对象。对于数值运算来说这种结构显然比较浪费内存和CPU计算时间。 
# 此外Python还提供了一个array模块，array对象和列表不同，它直接保存数值，和C语言的一维数组比较类似。
# 但是由于它不支持多维，也没有各种运算函数，因此也不适合做数值运算。 
# NumPy的诞生弥补了这些不足，NumPy提供了两种基本的对象：ndarray（N-dimensional array object）和 ufunc（universal function object）。
# ndarray是存储单一数据类型的多维数组，而ufunc则是能够对数组进行处理的函数。

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
#1.创建
import numpy as np
a=np.zeros(8)
b=np.array([1, 2, 3, 4],dtype=float)
c=np.array([[1,2,3],[4,5,6],[7,8,9]])

print a
print b
print c

[0. 0. 0. 0. 0. 0. 0. 0.]
[1. 2. 3. 4.]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
#2.数组的大小可以通过其shape
#一维数组（8，）
print a.shape
print a.shape[0]
print b.shape
print c.shape

(8,)
8
(4,)
(3, 3)


In [4]:
#3.reshape方法，可以创建一个改变了尺寸的新数组，原数组的shape保持不变：
#当某个轴的元素为-1时，将根据数组元素的个数自动计算此轴的长度
print a.reshape([2,4])
print a.reshape([2,-1])

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
#4.数组的元素类型可以通过dtype属性获得
#；通过astype修改元素类型
print a.dtype
print b.dtype


a=a.astype(np.int32)
print a.dtype

float64
int64
int32


In [37]:
#5.存取元素和Python的标准方法相同
b[1]    # 用整数作为下标可以获取数组中的某个元素
b[1:4]  # 用范围作为下标获取数组的一个切片，包括b[1]不包括b[4]
b[2]=10    # 下标还可以用来修改元素的值
b

array([ 1,  2, 10,  4])

In [43]:
#6.和Python的列表序列不同，通过下标范围获取的新的数组是原始数组的一个视图。它与原始数组共享同一块数据空间：
b=np.arange(1,5,1)
b2=b[1:3]
print 'b:', b
print 'b2', b2
b2[1]=-10
print 'b:', b
print 'b2', b2

b: [1 2 3 4]
b2 [2 3]
b: [  1   2 -10   4]
b2 [  2 -10]


In [42]:
#7.当使用整数序列对数组元素进行存取时，整数序列可以是列表或者数组。使用整数序列作为下标获得的数组不和原始数组共享数据空间。
a2=np.arange(1,10,1)
print 'a2', a2
a3=a2[[0,1,2]]
print 'a3:', a3
a3[0]=10
print 'a2', a2
print 'a3:', a3

a2 [1 2 3 4 5 6 7 8 9]
a3: [1 2 3]
a2 [1 2 3 4 5 6 7 8 9]
a3: [10  2  3]
